Cargo.toml, crates/oxvg_optimiser/src/jobs/convert_transform.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-10.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-11.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-12.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-13.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-7.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-8.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element-9.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_transform__add_attributes_to_svg_element.snap, crates/oxvg_optimiser/src/utils/mod.rs, crates/oxvg_optimiser/src/utils/transform.rs, crates/oxvg_path/src/command.rs, crates/oxvg_style/src/lib.rs
closes https://github.com/noahbald/oxvg/issues/7
=> feat(oxvg_optimiser): convert transform

crates/oxvg_ast/src/node.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_xml_proc_inst.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_xml_proc_inst__remove_xml_proc_inst-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_xml_proc_inst__remove_xml_proc_inst.snap
=> feat(oxvg_optimiser): #44 remove xml processing instructions

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_comments.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_comments__remove_comments-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_comments__remove_comments-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_comments__remove_comments.snap
=> feat(oxvg_optimiser): #19 remove comments

crates/oxvg_optimiser/src/jobs/collapse_groups.rs, crates/oxvg_optimiser/src/jobs/convert_ellipse_to_circle.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_doctype.rs, crates/oxvg_optimiser/src/jobs/remove_metadata.rs, crates/oxvg_optimiser/src/jobs/remove_xml_proc_inst.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_metadata__remove_metadata.snap
=> feat(oxvg_optimiser): #31 remove metadata

Cargo.lock, crates/oxvg_optimiser/Cargo.toml, crates/oxvg_optimiser/src/jobs/cleanup_enable_background.rs, crates/oxvg_optimiser/src/jobs/cleanup_ids.rs, crates/oxvg_optimiser/src/jobs/collapse_groups.rs, crates/oxvg_optimiser/src/jobs/convert_colors.rs, crates/oxvg_optimiser/src/jobs/convert_ellipse_to_circle.rs, crates/oxvg_optimiser/src/jobs/inline_styles.rs, crates/oxvg_optimiser/src/jobs/merge_styles.rs, crates/oxvg_optimiser/src/jobs/minify_styles.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_comments.rs, crates/oxvg_optimiser/src/jobs/remove_doctype.rs, crates/oxvg_optimiser/src/jobs/remove_metadata.rs, crates/oxvg_optimiser/src/jobs/remove_xml_proc_inst.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-10.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-7.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-8.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-9.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles.snap, crates/oxvg_optimiser/src/lib.rs, crates/oxvg_optimiser/src/utils/has_scripts.rs, crates/oxvg_optimiser/src/utils/mod.rs
=> feat(oxvg_optimiser): #13 minify styles

crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_non_inheritable_group_attrs.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_non_inheritable_group_attrs__remove_non_inheritable_group_attrs-2.snap.new, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_non_inheritable_group_attrs__remove_non_inheritable_group_attrs.snap
=> feat(oxvg_optimiser): #32 remove non-inheritable group attrs

crates/oxvg_ast/src/visitor.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_useless_stroke_and_fill.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_non_inheritable_group_attrs__remove_non_inheritable_group_attrs-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_useless_stroke_and_fill__remove_useless_stroke_and_fill-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_useless_stroke_and_fill__remove_useless_stroke_and_fill-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_useless_stroke_and_fill__remove_useless_stroke_and_fill-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_useless_stroke_and_fill__remove_useless_stroke_and_fill-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_useless_stroke_and_fill__remove_useless_stroke_and_fill.snap
=> feat(oxvg_optimiser): #41 remove useless stroke and fill

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_view_box.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_view_box__remove_view_box-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_view_box__remove_view_box-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_view_box__remove_view_box-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_view_box__remove_view_box-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_view_box__remove_view_box.snap
=> feat(oxvg_optimiser): #42 remove viewBox

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_empty_text.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_text__remove_empty_text-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_text__remove_empty_text-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_text__remove_empty_text.snap
=> feat(oxvg_optimiser): #29 remove empty text

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/move_group_attrs_to_elems.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__move_group_attrs_to_elems-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__move_group_attrs_to_elems-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__move_group_attrs_to_elems-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__move_group_attrs_to_elems-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__move_group_attrs_to_elems-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__move_group_attrs_to_elems.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__move_group_attrs_to_elems__remove_empty_text.snap
=> feat(oxvg_optimiser): #15 move group attrs to elements

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_empty_attrs.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_attrs__remove_empty_attrs-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_attrs__remove_empty_attrs.snap
=> feat(oxvg_optimiser): #27 remove empty attrs

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_empty_containers.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers-7.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_empty_containers__remove_empty_containers.snap
=> feat(oxvg_optimiser): #28 remove empty containers

crates/oxvg_ast/src/attribute.rs, crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__sort_attrs__sort_attrs-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__sort_attrs__sort_attrs-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__sort_attrs__sort_attrs-4.snap.new, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__sort_attrs__sort_attrs.snap, crates/oxvg_optimiser/src/jobs/sort_attrs.rs
=> feat(oxvg_optimise): #47 sort attrs

crates/oxvg_ast/src/element.rs, crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_ast/src/name.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__sort_attrs__sort_attrs-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__sort_defs_children__sort_defs_children.snap, crates/oxvg_optimiser/src/jobs/sort_defs_children.rs
=> feat(oxvg_optimiser): #48 sort defs children

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_title.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_title__remove_title.snap.new
=> feat(oxvg_optimiser): #37 remove title

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_desc.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_desc__remove_desc.snap.new
=> feat(oxvg_optimiser): #21 remove desc

Cargo.toml, crates/oxvg/src/args.rs, crates/oxvg_ast/src/element.rs, crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_ast/src/node.rs, crates/oxvg_ast/src/style.rs, crates/oxvg_ast/src/visitor.rs, crates/oxvg_optimiser/benches/default_jobs.rs, crates/oxvg_optimiser/benches/path.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/prefix_ids.rs, crates/oxvg_optimiser/src/jobs/remove_hidden_elems.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-10.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-11.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-12.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-13.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-7.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-8.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids-9.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__prefix_ids__prefix_ids.snap
=> feat(oxvg_optimiser): #16 prefix ids

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_attributes_by_selector.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attributes_by_selector__remove_attributes_by_selector-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attributes_by_selector__remove_attributes_by_selector-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attributes_by_selector__remove_attributes_by_selector.snap
=> feat(oxvg_optimiser): #17 remove attributes by selector

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_attrs.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attrs__remove_attrs-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attrs__remove_attrs-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attrs__remove_attrs-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attrs__remove_attrs-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_attrs__remove_attrs.snap
=> feat(oxvg_optimiser): #18 remove attrs

crates/oxvg_ast/src/visitor.rs, crates/oxvg_optimiser/src/jobs/collapse_groups.rs, crates/oxvg_optimiser/src/jobs/inline_styles.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/move_elems_attrs_to_group.rs, crates/oxvg_optimiser/src/jobs/remove_empty_containers.rs, crates/oxvg_optimiser/src/jobs/remove_useless_stroke_and_fill.rs, crates/oxvg_optimiser/src/jobs/reuse_paths.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__reuse_paths__reuse_paths-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__reuse_paths__reuse_paths-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__reuse_paths__reuse_paths-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__reuse_paths__reuse_paths-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__reuse_paths__reuse_paths-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__reuse_paths__reuse_paths.snap
=> feat(oxvg_optimiser): #46 reuse paths

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_raster_images.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_raster_images__remove_raster_images-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_raster_images__remove_raster_images.snap
=> feat(oxvg_optimiser): #34 remove raster images

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_off_canvas_paths.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_off_canvas_paths__remove_off_canvas_paths-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_off_canvas_paths__remove_off_canvas_paths-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_off_canvas_paths__remove_off_canvas_paths-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_off_canvas_paths__remove_off_canvas_paths-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_off_canvas_paths__remove_off_canvas_paths-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_off_canvas_paths__remove_off_canvas_paths.snap
=> feat(oxvg_optimiser): #33 remove off canvas paths

crates/oxvg_ast/src/element.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_dimensions.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_dimensions__remove_dimensions-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_dimensions__remove_dimensions-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_dimensions__remove_dimensions-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_dimensions__remove_dimensions-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_dimensions__remove_dimensions-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_dimensions__remove_dimensions.snap
=> feat(oxvg_optimiser): #23 remove dimensions

Cargo.lock, crates/oxvg/Cargo.toml, crates/oxvg_ast/Cargo.toml, crates/oxvg_collections/Cargo.toml, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_elements_by_attr.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr-7.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_elements_by_attr__remove_elements_by_attr.snap
=> feat(oxvg_optimiser): #26 remove elements by attr

crates/oxvg_ast/src/atom.rs, crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_ast/src/node.rs, crates/oxvg_collections/src/collections.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_scripts.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_scripts__remove_scripts-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_scripts__remove_scripts-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_scripts__remove_scripts-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_scripts__remove_scripts-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_scripts__remove_scripts.snap
=> feat(oxvg_optimiser): #35 remove script element

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_scripts.rs, crates/oxvg_optimiser/src/jobs/remove_style_element.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_style_element__remove_style_element.snap
=> fix(oxvg_optimiser): #36 remove style element

crates/oxvg_optimiser/src/utils/cleanup_values.rs
=> fix(oxvg_optimiser): #51 remove pointless `d` cleanup

crates/oxvg_ast/src/document.rs, crates/oxvg_ast/src/visitor.rs, crates/oxvg_optimiser/src/jobs/apply_transforms.rs, crates/oxvg_optimiser/src/jobs/cleanup_ids.rs, crates/oxvg_optimiser/src/jobs/cleanup_list_of_values.rs, crates/oxvg_optimiser/src/jobs/cleanup_numeric_values.rs, crates/oxvg_optimiser/src/jobs/convert_path_data.rs, crates/oxvg_optimiser/src/jobs/convert_transform.rs, crates/oxvg_optimiser/src/jobs/inline_styles.rs, crates/oxvg_optimiser/src/jobs/merge_paths.rs, crates/oxvg_optimiser/src/jobs/merge_styles.rs, crates/oxvg_optimiser/src/jobs/minify_styles.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_empty_containers.rs, crates/oxvg_optimiser/src/jobs/remove_hidden_elems.rs, crates/oxvg_optimiser/src/jobs/remove_unknowns_and_defaults.rs, crates/oxvg_optimiser/src/jobs/remove_useless_stroke_and_fill.rs
Closes #93 
Closes #90 
Improves benchmarks by 7% - 20%
=> chore(oxvg_optimiser): #93,#90 reduce unnecessary smart pointers & options

crates/oxvg_optimiser/src/jobs/convert_colors.rs
=> chore(oxvg_optimiser): #112 update convertColors to use lightningcss visitor

Cargo.lock, Cargo.toml, crates/oxvg_ast/Cargo.toml, crates/oxvg_ast/src/attribute.rs, crates/oxvg_ast/src/element.rs, crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_ast/src/node.rs, crates/oxvg_ast/src/style.rs, crates/oxvg_ast/src/visitor.rs, crates/oxvg_collections/Cargo.toml
Pre-requisite for #111 -- required for library release
=> fix!: mend broken feature cfgs

crates/oxvg_ast/src/attribute.rs, crates/oxvg_ast/src/element.rs, crates/oxvg_ast/src/implementations/markup5ever.rs, crates/oxvg_ast/src/visitor.rs
=> feat(oxvg_ast)!: #113 expose ast ref lifetimes

crates/oxvg_optimiser/src/jobs/convert_path_data.rs, crates/oxvg_optimiser/src/jobs/merge_paths.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_path_data__convert_path_data-30.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__merge_paths__merge_paths-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__merge_paths__merge_paths.snap, crates/oxvg_path/src/convert/filter.rs
=> fix: #121 path optimisation bugs

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_unused_n_s.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s-6.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s-7.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_unused_n_s__remove_unused_n_s.snap
=> feat(oxvg_optimiser): #39 remove unused ns

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_x_m_l_n_s.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_x_m_l_n_s__remove_xmlns.snap
=> feat(oxvg_optimiser): #43 remove xmlns

crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/remove_xlink.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_xlink__remove_xlink-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_xlink__remove_xlink-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_xlink__remove_xlink-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__remove_xlink__remove_xlink.snap
=> feat(oxvg_optimiser): #45 remove xlink

packages/napi/README.md, packages/napi/src/lib.rs, packages/wasm/README.md, packages/wasm/src/lib.rs, readme.md
=> docs: #136 add/update readmes for bindings

Cargo.lock, crates/oxvg_optimiser/src/jobs/mod.rs, packages/napi/Cargo.toml, packages/napi/README.md, packages/napi/index.d.ts, packages/napi/index.js, packages/napi/src/lib.rs, packages/napi/test.js, packages/wasm/README.md, packages/wasm/src/lib.rs, packages/wasm/test.cjs, tsconfig.json
=> feat: add helper for reusing svgo config

crates/oxvg_optimiser/src/jobs/inline_styles.rs, crates/oxvg_optimiser/src/jobs/minify_styles.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__inline_styles__inline_styles-29.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-11.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__minify_styles__minify_styles-12.snap
=> fix: #152 fix removing selectors when matching multiple items

crates/oxvg_path/src/convert/filter/arc.rs, crates/oxvg_path/src/lib.rs
maybe can close: https://github.com/noahbald/oxvg/issues/155
=> add feature(core_float_math)

crates/oxvg_optimiser/src/utils/cleanup_values.rs
=> fix(optimiser): #161 fix behaviour with "new" in cleanup numeric values

crates/oxvg_ast/src/atom.rs, crates/oxvg_optimiser/src/jobs/convert_style_to_attrs.rs, crates/oxvg_optimiser/src/jobs/mod.rs, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_style_to_attrs__convert_style_to_attrs-2.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_style_to_attrs__convert_style_to_attrs-3.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_style_to_attrs__convert_style_to_attrs-4.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_style_to_attrs__convert_style_to_attrs-5.snap, crates/oxvg_optimiser/src/jobs/snapshots/oxvg_optimiser__jobs__convert_style_to_attrs__convert_style_to_attrs.snap
=> feat(oxvg_optimiser): #148 convert style to attrs

readme.md
You need to cd into the directory for the following commands to work
=> Fix building instructions
